using Repositories.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Repositories.Interfaces
{
    public interface IDepositRepository
    {
        public Task<DepositInformation> GetDepositInformationById(string depositId);
        public Task<List<DepositInformation>> GetAllDepositInformation();
        public Task<DepositInformation> GetDepositInformationByUserId(string userId);
        public Task<string> GetLatestDepositInformationIdAsync();
        public Task<string> AutoGenerateDepositInformationId();
        public Task<DepositInformation> CreateDepositInformation(DepositInformation deposit);
        public Task<dynamic> UpdateDepositInformation(DepositInformation deposit);

    }
}
